package com.rahulpahuja.waves.ui.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Welcome : Screen("welcome")
    object TrackProgress : Screen("track_progress")
    object CreatePersona : Screen("create_persona")
    object AllSet : Screen("all_set")
    object Login : Screen("login")
    object ForgotPassword : Screen("forgot_password")
    object Home : Screen("home")
    object Notifications : Screen("notifications")
    object AdminDashboard : Screen("admin_dashboard")
    object AdminSettings : Screen("admin_settings")
    object Students : Screen("students")
    object CreateStudent : Screen("create_student")
    object NewCashEntry : Screen("new_cash_entry")
    object CreateSession : Screen("create_session")
    object ManageBookings : Screen("manage_bookings")
    object HelpSupport : Screen("help_support")
    object StudentDashboard : Screen("student_dashboard")
    object StudentSettings : Screen("student_settings")
    object PaymentHistory : Screen("payment_history")
    object ArtistProfile : Screen("artist_profile")
    object Chat : Screen("chat")
    object MediaGallery : Screen("media_gallery")
    object Attendance : Screen("attendance")
    object Settings : Screen("settings")
    object ProfileSettings : Screen("profile_settings")
    object ArtistRadar : Screen("artist_radar")
    object PublicArtistProfile : Screen("public_artist_profile")
    object StudioSchedule : Screen("studio_schedule")
    object WelcomeToTheBooth : Screen("welcome_to_the_booth")
    object ManageStudentLifecycle : Screen("manage_student_lifecycle")
    object ProfileSetup : Screen("profile_setup")
    object AdminWelcome : Screen("admin_welcome")
}
